users:
  chidolue:
    username: "Chidolue Zikora"
    articleIds:
      - 1
    commentIds: []
  spongebob:
    username: "SpongeBob SquarePants"
    articleIds:
      - 2
    commentIds:
      - 1
  morty:
    username: Morty
    articleIds: []
    commentIds: []
articles:
  '1':
    id: 1
    title: "Trending: The Scoop"
    url: 'https://chidoluezikora.github.io/project-3-the-scoop-start/'
    username: chidolue
    commentIds: []
    upvotedBy: []
    downvotedBy: []
    comments: []
  '2':
    id: 2
    title: "Beautiful Bikini Bottom"
    url: 'https://en.wikipedia.org/wiki/SpongeBob_SquarePants/'
    username: spongebob
    commentIds:
      - 1
    upvotedBy: 
      - chidolue
    downvotedBy: []
    comments:
      - &ref_0
        id: 1
        body: Hi
        username: morty
        articleId: 2
        upvotedBy: []
        downvotedBy: []
nextArticleId: 3
comments:
  '1': *ref_0
nextCommentId: 2
